import sys

filepath = r'c:\Users\admin\Documents\weather\script.js'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# The section started around line 670 (0-indexed 669)
# and ended just before renderRoadDashboard which was around line 1106 (0-indexed 1105)

# I will find the exact indices
start_idx = -1
end_idx = -1

for i, line in enumerate(lines):
    if "function getNearestStationData() {" in line:
        start_idx = i
    if "function renderRoadDashboard() {" in line:
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    print(f"Found section from line {start_idx+1} to {end_idx+1}")
    
    clean_code = [
        "  function getNearestStationData() {\n",
        "    const stations = generateHydroData();\n",
        "    const tideStations = stations.filter(s => s.waterLevel && Number.isFinite(s.lat) && Number.isFinite(s.lon));\n",
        "    if (!tideStations.length) return null;\n",
        "    return tideStations.reduce((best, s) => {\n",
        "      const d = haversine(RT.lat, RT.lon, s.lat, s.lon);\n",
        "      return !best || d < best.dist ? { s, dist: d } : best;\n",
        "    }, null)?.s || null;\n",
        "  }\n",
        "\n",
        "  function renderAquaAlert() {\n",
        "    const banner = $('aquaAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const nextItems = items.slice(0, 2);\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "    const heatIndex = cur.main?.feels_like ?? curTemp;\n",
        "\n",
        "    const hasStorm = nextItems.some(i => (i.weather?.id || 0) >= 200 && (i.weather?.id || 0) < 300);\n",
        "    const hasWind = curWind >= 28;\n",
        "    const hasHeavyRain = curRain >= 10 || curPop >= 70;\n",
        "    const hasHeat = heatIndex >= 35;\n",
        "\n",
        "    const nearestSt = getNearestStationData();\n",
        "    const waterLvl = nearestSt ? parseFloat(nearestSt.waterLevel) : null;\n",
        "    const hasHighTide = waterLvl != null && waterLvl > 2.5;\n",
        "    const warnHighTide = waterLvl != null && waterLvl > 2.0 && waterLvl <= 2.5;\n",
        "\n",
        "    const warnWind = curWind >= 22;\n",
        "    const warnRain = curRain >= 5 || curPop >= 50;\n",
        "    const warnHeat = heatIndex >= 31;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét gây sốc nước');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 10mm/70%)`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh (${curWind.toFixed(1)}km/h ≥ 28km/h)`);\n",
        "    if (hasHeat) details.push(`⚠️ Nguy hiểm: Nắng nóng (${heatIndex.toFixed(1)}°C ≥ 35°C) — Giảm oxy, tăng nhiệt nước`);\n",
        "    if (hasHighTide) details.push(`⚠️ Nguy hiểm: Mực triều (${waterLvl.toFixed(2)}m > 2.5m) — Cảnh báo ngập vùng nuôi tôm!`);\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Mưa/ẩm (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 5mm/50%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh (${curWind.toFixed(1)}km/h ≥ 22km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt tăng (${heatIndex.toFixed(1)}°C ≥ 31°C)`);\n",
        "    if (!hasHighTide && warnHighTide) warnDetails.push(`⚡ Cảnh báo: Mực nước cao (${waterLvl.toFixed(2)}m > 2.0m)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const locLabel = wardInfo ? `${wardInfo.name} · ${wardInfo.district}` : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Khuyến cáo Thủy sản (Nguy hiểm)</strong>: Rủi ro cao tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}${nearestSt ? ' (Trạm: ' + nearestSt.name + ')' : ''}</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Khuyến cáo Thủy sản (Cảnh báo)</strong>: Cần theo dõi tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Thủy sản ổn định</strong>: Điều kiện thuận lợi tại vị trí GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí: ${locLabel} (GPS) · Nguồn: OpenWeatherMap</span>`;\n",
        "    }\n",
        "  }\n",
        "\n",
        "  function renderFarmAlert() {\n",
        "    const banner = $('farmAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const nextItems = items.slice(0, 2);\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "\n",
        "    const hasStorm = nextItems.some(i => (i.weather?.id || 0) >= 200 && (i.weather?.id || 0) < 300);\n",
        "    const hasHeat = curTemp >= 35 || nextItems.slice(0,1).some(i => i.temp >= 35);\n",
        "    const hasWind = curWind >= 28;\n",
        "    const hasHeavyRain = curRain >= 10 || curPop >= 70;\n",
        "\n",
        "    const warnHeat = curTemp >= 32 || nextItems.slice(0,1).some(i => i.temp >= 32);\n",
        "    const warnWind = curWind >= 22;\n",
        "    const warnRain = curRain >= 5 || curPop >= 50;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét (mã 2xx)');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 10mm/70%)`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh (${curWind.toFixed(1)} km/h ≥ 28 km/h)`);\n",
        "    if (hasHeat) details.push(`⚠️ Nguy hiểm: Nắng nóng (${curTemp.toFixed(1)}°C ≥ 35°C) — Tưới nước buổi sáng sớm, che lưới cho cây trồng`);\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Mưa vừa/xác suất cao (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 5mm/50%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh (${curWind.toFixed(1)} km/h ≥ 22 km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt độ cao (${curTemp.toFixed(1)}°C ≥ 32°C)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const crops = getCropsForWard(wardInfo);\n",
        "    const locLabel = wardInfo\n",
        "      ? `${wardInfo.name} · ${wardInfo.district}`\n",
        "      : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Cảnh báo Nông nghiệp (Nguy hiểm)</strong>: Điều kiện bất lợi tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `${crops.length ? ` Cây trồng chính: ${crops.join(', ')}.` : ''}` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel} · Nguồn: OpenWeatherMap</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Cảnh báo Nông nghiệp (Theo dõi)</strong>: Có tín hiệu cần lưu ý tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel} · Nguồn: OpenWeatherMap</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Nông nghiệp ổn định</strong>: Điều kiện thuận lợi tại GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel} · Cây trồng: ${crops.join(', ') || 'Đang cập nhật'}</span>`;\n",
        "    }\n",
        "  }\n",
        "\n",
        "  function renderRoadAlert() {\n",
        "    const banner = $('roadAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "    const visibilityKm = cur.visibility != null ? (cur.visibility / 1000) : null;\n",
        "\n",
        "    const nextItems = items.slice(0, 2);\n",
        "    const hasStorm = nextItems.some(i => (i.weather?.id || 0) >= 200 && (i.weather?.id || 0) < 300);\n",
        "    const hasWind = curWind >= 28;\n",
        "    const hasHeavyRain = curRain >= 10 || curPop >= 70;\n",
        "    const hasHeat = curTemp >= 35;\n",
        "    const hasLowVis = visibilityKm != null && visibilityKm < 2;\n",
        "\n",
        "    const warnWind = curWind >= 22;\n",
        "    const warnRain = curRain >= 5 || curPop >= 50;\n",
        "    const warnHeat = curTemp >= 31;\n",
        "    const warnVis = visibilityKm != null && visibilityKm < 4;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét, hạn chế di chuyển');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 10mm/70%) — Đường ngập`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh (${curWind.toFixed(1)}km/h ≥ 28km/h) — Chú ý vật cản`);\n",
        "    if (hasHeat) details.push(`⚠️ Nguy hiểm: Nắng nóng (${curTemp.toFixed(1)}°C ≥ 35°C) — Dễ mất nước`);\n",
        "    if (hasLowVis) details.push(`⚠️ Nguy hiểm: Tầm nhìn thấp (${visibilityKm.toFixed(1)}km < 2km) — Bật đèn`);\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Có mưa (${curRain.toFixed(1)}mm/h / ${curPop}% ≥ 5mm/50%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh (${curWind.toFixed(1)}km/h ≥ 22km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt cao (${curTemp.toFixed(1)}°C ≥ 31°C)`);\n",
        "    if (!hasLowVis && warnVis) warnDetails.push(`⚡ Cảnh báo: Tầm nhìn giảm (${visibilityKm.toFixed(1)}km < 4km)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const locLabel = wardInfo ? `${wardInfo.name} · ${wardInfo.district}` : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông (Nguy hiểm)</strong>: Điều kiện không an toàn tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông (Cảnh báo)</strong>: Chú ý quan sát tại vị trí GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông ổn định</strong>: Điều kiện thuận lợi tại GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    }\n",
        "  }\n",
        "\n"
    ]
    
    new_lines = lines[:start_idx] + clean_code + lines[end_idx:]
    
    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        f.writelines(new_lines)
    
    print("Successfully cleaned and updated the section.")
else:
    print("FAILED to find start/end marks.")
    if start_idx == -1: print("Start mark missing.")
    if end_idx == -1: print("End mark missing.")
