import sys

filepath = r'c:\Users\admin\Documents\weather\script.js'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the start of the section (getCropsForWard is usually safe)
start_idx = -1
for i, line in enumerate(lines):
    if "function getCropsForWard(ward) {" in line:
        start_idx = i
        break

# Find the end of the section (just after renderAquaDashboard ends)
end_idx = -1
for i, line in enumerate(lines):
    if i > start_idx and "function renderAquaDashboard() {" in line:
        # Scan forward for the closing brace of renderAquaDashboard
        brace_count = 0
        started = False
        for j in range(i, len(lines)):
            brace_count += lines[j].count('{')
            brace_count -= lines[j].count('}')
            if '{' in lines[j]: started = True
            if started and brace_count == 0:
                end_idx = j + 1
                break
        if end_idx != -1: break

if start_idx != -1 and end_idx != -1:
    print(f"Replacing section from line {start_idx+1} to {end_idx+1}")
    
    clean_code = [
        "  function getCropsForWard(ward) {\n",
        "    const data = window.CROPS_BY_WARD || {};\n",
        "    const wards = data.wards || {};\n",
        "    const districts = data.districts || {};\n",
        "    if (ward?.id && wards[String(ward.id)]) return wards[String(ward.id)];\n",
        "    if (ward?.district && districts[ward.district]) return districts[ward.district];\n",
        "    return data.default || [];\n",
        "  }\n",
        "\n",
        "  function getNearestStationData() {\n",
        "    const stations = generateHydroData();\n",
        "    const tideStations = stations.filter(s => s.waterLevel && Number.isFinite(s.lat) && Number.isFinite(s.lon));\n",
        "    if (!tideStations.length) return null;\n",
        "    return tideStations.reduce((best, s) => {\n",
        "      const d = haversine(RT.lat, RT.lon, s.lat, s.lon);\n",
        "      return !best || d < best.dist ? { s, dist: d } : best;\n",
        "    }, null)?.s || null;\n",
        "  }\n",
        "\n",
        "  function isDayNow() {\n",
        "    const sys = RT.current?.sys;\n",
        "    if (sys?.sunrise && sys?.sunset) {\n",
        "      const now = Date.now() / 1000;\n",
        "      return now >= sys.sunrise && now < sys.sunset;\n",
        "    }\n",
        "    const h = new Date().getHours();\n",
        "    return h >= 6 && h < 18;\n",
        "  }\n",
        "\n",
        "  function renderAquaAlert() {\n",
        "    const banner = $('aquaAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const cur = RT.current;\n",
        "    const nextHour = items[0] || cur;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const nextTemp = nextHour.temp ?? curTemp;\n",
        "    const heatIndex = cur.main?.feels_like ?? curTemp;\n",
        "    const nextHeatIndex = nextHour.feels_like ?? nextTemp;\n",
        "    \n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const nextWind = mps2kmh(nextHour.wind || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const nextRain = nextHour.rain || curRain;\n",
        "    const nextPop = Math.round((nextHour.pop || 0) * 100);\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const hasStorm = (nextHour.weather?.id || 0) >= 200 && (nextHour.weather?.id || 0) < 300;\n",
        "    const hasWind = nextWind >= 28;\n",
        "    const hasHeavyRain = nextRain >= 10 || nextPop >= 70;\n",
        "    const hasHeat = nextHeatIndex >= 35;\n",
        "\n",
        "    const nearestSt = getNearestStationData();\n",
        "    const waterLvl = nearestSt ? parseFloat(nearestSt.waterLevel) : null;\n",
        "    const hasHighTide = waterLvl != null && waterLvl > 2.5;\n",
        "    const warnHighTide = waterLvl != null && waterLvl > 2.0 && waterLvl <= 2.5;\n",
        "\n",
        "    const warnWind = nextWind >= 22;\n",
        "    const warnRain = nextRain >= 5 || nextPop >= 50;\n",
        "    const warnHeat = nextHeatIndex >= 31;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét gây sốc nước 60 phút tới');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}% ≥ 10mm/70%)`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh 60 phút tới (${nextWind.toFixed(1)}km/h ≥ 28km/h)`);\n",
        "    if (hasHeat) {\n",
        "        const advice = isDay ? \"Che mát ao nuôi, tăng sục khí oxy\" : \"Tăng sục khí oxy (nhiệt nước còn cao), kiểm tra oxy hòa tan\";\n",
        "        details.push(`⚠️ Nguy hiểm: Nắng nóng cực đại (${nextHeatIndex.toFixed(1)}°C ≥ 35°C) — ${advice}`);\n",
        "    }\n",
        "    if (hasHighTide) {\n",
        "        const caution = isDay ? \"Gia cố bờ bao, kiểm tra cống\" : \"Kiểm tra bờ bao bằng đèn pin, đề phòng sạt lở túi khí ban đêm\";\n",
        "        details.push(`⚠️ Nguy hiểm: Mực triều (${waterLvl.toFixed(2)}m > 2.5m) — Cảnh báo ngập vùng nuôi tôm! ${caution}`);\n",
        "    }\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Biến động độ mặn 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh 60 phút tới (${nextWind.toFixed(1)}km/h ≥ 22km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt tăng 60 phút tới (${nextHeatIndex.toFixed(1)}°C ≥ 31°C)`);\n",
        "    if (!hasHighTide && warnHighTide) warnDetails.push(`⚡ Cảnh báo: Mực nước cao (${waterLvl.toFixed(2)}m > 2.0m)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const locLabel = wardInfo ? `${wardInfo.name} · ${wardInfo.district}` : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Thủy sản (60 phút tới - Nguy hiểm)</strong>: Rủi ro cao tại vị trí GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}${nearestSt ? ' (Trạm: ' + nearestSt.name + ')' : ''}</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Thủy sản (60 phút tới - Cảnh báo)</strong>: Theo dõi tại vị trí GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Thủy sản ổn định (60 phút tới)</strong>: Không có rủi ro tại GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí: ${locLabel} (GPS) · Nguồn: OpenWeatherMap</span>`;\n",
        "    }\n",
        "  }\n",
        "\n",
        "  function renderFarmAlert() {\n",
        "    const banner = $('farmAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const cur = RT.current;\n",
        "    const nextHour = items[0] || cur;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const nextHourTemp = nextHour.temp ?? curTemp;\n",
        "    const nextWind = mps2kmh(nextHour.wind || 0);\n",
        "    const nextRain = nextHour.rain || 0;\n",
        "    const nextPop = Math.round((nextHour.pop || 0) * 100);\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const hasStorm = (nextHour.weather?.id || 0) >= 200 && (nextHour.weather?.id || 0) < 300;\n",
        "    const hasHeat = nextHourTemp >= 35;\n",
        "    const hasWind = nextWind >= 28;\n",
        "    const hasHeavyRain = nextRain >= 10 || nextPop >= 70;\n",
        "\n",
        "    const warnHeat = nextHourTemp >= 32;\n",
        "    const warnWind = nextWind >= 22;\n",
        "    const warnRain = nextRain >= 5 || nextPop >= 50;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét 60 phút tới (mã 2xx)');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}% >= 10mm/70%)`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh 60 phút tới (${nextWind.toFixed(1)} km/h >= 28 km/h)`);\n",
        "    if (hasHeat) {\n",
        "      const advice = isDay ? \"Tưới nước buổi sáng sớm, che lưới cho cây trồng\" : \"Theo dõi nhiệt đất, chuẩn bị tưới sáng sớm mai\";\n",
        "      details.push(`⚠️ Nguy hiểm: Nắng nóng cực đại (${nextHourTemp.toFixed(1)}°C >= 35°C) — ${advice}`);\n",
        "    }\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Mưa/xác suất cao 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}% >= 5mm/50%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh 60 phút tới (${nextWind.toFixed(1)} km/h >= 22 km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt tăng 60 phút tới (${nextHourTemp.toFixed(1)}°C >= 32°C)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const crops = getCropsForWard(wardInfo);\n",
        "    const locLabel = wardInfo ? `${wardInfo.name} · ${wardInfo.district}` : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Cảnh báo Nông nghiệp (60 phút tới)</strong>: Nguy hiểm tại vị trí GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `${crops.length ? ` Cây trồng chính: ${crops.join(', ')}.` : ''}` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel} · Cây trồng: ${crops.join(', ') || 'Đang cập nhật'}</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Cảnh báo Nông nghiệp (60 phút tới)</strong>: Theo dõi tại vị trí GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Nông nghiệp ổn định (60 phút tới)</strong>: Thuận lợi tại vị trí GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel} · Cây trồng: ${crops.join(', ') || 'Đang cập nhật'}</span>`;\n",
        "    }\n",
        "  }\n",
        "\n",
        "  function renderRoadAlert() {\n",
        "    const banner = $('roadAlert');\n",
        "    if (!banner) return;\n",
        "\n",
        "    const items = getInterpolated24h();\n",
        "    if (!items.length || !RT.current) {\n",
        "      banner.hidden = true;\n",
        "      return;\n",
        "    }\n",
        "\n",
        "    const cur = RT.current;\n",
        "    const nextHour = items[0] || cur;\n",
        "    const curTemp = cur.main?.temp ?? 0;\n",
        "    const nextTemp = nextHour.temp ?? curTemp;\n",
        "    const nextWind = mps2kmh(nextHour.wind || 0);\n",
        "    const nextRain = nextHour.rain || 0;\n",
        "    const nextPop = Math.round((nextHour.pop || 0) * 100);\n",
        "    const visibilityKm = cur.visibility != null ? (cur.visibility / 1000) : null;\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const hasStorm = (nextHour.weather?.id || 0) >= 200 && (nextHour.weather?.id || 0) < 300;\n",
        "    const hasWind = nextWind >= 28;\n",
        "    const hasHeavyRain = nextRain >= 10 || nextPop >= 70;\n",
        "    const hasHeat = nextTemp >= 35;\n",
        "    const hasLowVis = visibilityKm != null && visibilityKm < 2;\n",
        "\n",
        "    const warnWind = nextWind >= 22;\n",
        "    const warnRain = nextRain >= 5 || nextPop >= 50;\n",
        "    const warnHeat = nextTemp >= 31;\n",
        "    const warnVis = visibilityKm != null && visibilityKm < 4;\n",
        "\n",
        "    const details = [];\n",
        "    if (hasStorm) details.push('⚠️ Nguy hiểm: Dông sét 60 phút tới, hạn chế di chuyển');\n",
        "    if (hasHeavyRain) details.push(`⚠️ Nguy hiểm: Mưa lớn 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}% >= 10mm/70%)`);\n",
        "    if (hasWind) details.push(`⚠️ Nguy hiểm: Gió mạnh 60 phút tới (${nextWind.toFixed(1)}km/h >= 28km/h)`);\n",
        "    if (hasHeat) details.push(`⚠️ Nguy hiểm: Nắng nóng cực đại (${nextTemp.toFixed(1)}°C >= 35°C) — ${isDay ? \"Dễ mất nước, say nắng\" : \"Cần bù nước, nhiệt đường còn cao\"}`);\n",
        "    if (hasLowVis) {\n",
        "        const advice = isDay ? \"Bật đèn sương mù, đi chậm\" : \"Bật đèn chiếu sáng xa/gần, chú ý quan sát vật cản\";\n",
        "        details.push(`⚠️ Nguy hiểm: Tầm nhìn thấp (${visibilityKm.toFixed(1)}km < 2km) — ${advice}`);\n",
        "    }\n",
        "\n",
        "    const warnDetails = [];\n",
        "    if (!hasHeavyRain && warnRain) warnDetails.push(`⚡ Cảnh báo: Có mưa 60 phút tới (${nextRain.toFixed(1)}mm/h / ${nextPop}%)`);\n",
        "    if (!hasWind && warnWind) warnDetails.push(`⚡ Cảnh báo: Gió khá mạnh 60 phút tới (${nextWind.toFixed(1)}km/h >= 22km/h)`);\n",
        "    if (!hasHeat && warnHeat) warnDetails.push(`⚡ Cảnh báo: Nhiệt cao 60 phút tới (${nextTemp.toFixed(1)}°C >= 31°C)`);\n",
        "    if (!hasLowVis && warnVis) warnDetails.push(`⚡ Cảnh báo: Tầm nhìn giảm 60 phút tới (${visibilityKm.toFixed(1)}km < 4km)`);\n",
        "\n",
        "    const wardInfo = window.WARDS_COORDS ? nearestWard(RT.lat, RT.lon)?.ward : null;\n",
        "    const locLabel = wardInfo ? `${wardInfo.name} · ${wardInfo.district}` : (RT.name || 'Khu vực hiện tại');\n",
        "\n",
        "    if (details.length) {\n",
        "      banner.classList.remove('is-safe', 'is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'danger';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông (60 phút tới - Nguy hiểm)</strong>: Điều kiện không an toàn tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + details.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else if (warnDetails.length) {\n",
        "      banner.classList.remove('is-safe'); banner.classList.add('is-warn');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'warn';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông (60 phút tới - Cảnh báo)</strong>: Chú ý quan sát tại GPS.` +\n",
        "        `<div class=\"farm-detail\">` + warnDetails.map(d => `• ${d}`).join('<br>') + `</div>` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    } else {\n",
        "      banner.classList.remove('is-warn'); banner.classList.add('is-safe');\n",
        "      banner.hidden = false;\n",
        "      banner.dataset.level = 'ok';\n",
        "      banner.innerHTML =\n",
        "        `<strong>Giao thông ổn định (60 phút tới)</strong>: Thuận lợi tại GPS.` +\n",
        "        `<span class=\"farm-meta\">Vị trí GPS: ${locLabel}</span>`;\n",
        "    }\n",
        "  }\n",
        "\n",
        "  function renderRoadDashboard() {\n",
        "    const table = $('roadDashTable');\n",
        "    if (!table || !RT.current) return;\n",
        "    const tbody = table.querySelector('tbody');\n",
        "    if (!tbody) return;\n",
        "\n",
        "    const next = getInterpolated24h().slice(0, 1);\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? null;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "    const visibilityKm = cur.visibility != null ? (cur.visibility / 1000) : null;\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const nxt = next[0] || {};\n",
        "    const nxtTemp = nxt.temp ?? curTemp;\n",
        "    const nxtWind = mps2kmh(nxt.wind || (cur.wind?.speed ?? 0));\n",
        "    const nxtPop = Math.round((nxt.pop || 0) * 100);\n",
        "    const nxtHasStorm = (nxt.weather?.id || 0) >= 200 && (nxt.weather?.id || 0) < 300;\n",
        "\n",
        "    const rows = [\n",
        "      {\n",
        "        name: 'Mưa',\n",
        "        threshold: '≥10mm/h hoặc ≥70%',\n",
        "        current: `${curRain.toFixed(1)} mm/h \u00b7 ${curPop}%`,\n",
        "        trend: `60 phút tới: ${nxtPop}%`,\n",
        "        level: (curRain >= 10 || nxtPop >= 70) ? 'danger' : (nxtPop >= 50 ? 'warn' : 'ok'),\n",
        "        advice: (curRain >= 10 || nxtPop >= 70) ? 'Hạn chế đi đường, dễ ngập' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Gió',\n",
        "        threshold: '≥28 km/h',\n",
        "        current: `${curWind} km/h`,\n",
        "        trend: `60 phút tới: ${nxtWind} km/h`,\n",
        "        level: nxtWind >= 28 ? 'danger' : (nxtWind >= 22 ? 'warn' : 'ok'),\n",
        "        advice: nxtWind >= 28 ? 'Đi chậm, tránh cây lớn' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Dông sét',\n",
        "        threshold: 'Mã 2xx',\n",
        "        current: nxtHasStorm ? 'Có dông' : 'Không',\n",
        "        trend: nxtHasStorm ? '60 phút tới: có khả năng' : 'Ổn định',\n",
        "        level: nxtHasStorm ? 'danger' : 'ok',\n",
        "        advice: nxtHasStorm ? 'Tránh di chuyển ngoài trời' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Tầm nhìn',\n",
        "        threshold: '<2 km',\n",
        "        current: visibilityKm != null ? `${visibilityKm.toFixed(1)} km` : '\u2014',\n",
        "        trend: visibilityKm != null ? `Dự báo: ~${visibilityKm.toFixed(1)} km` : '\u2014',\n",
        "        level: visibilityKm != null && visibilityKm < 2 ? 'danger' : (visibilityKm != null && visibilityKm < 4 ? 'warn' : 'ok'),\n",
        "        advice: visibilityKm != null && visibilityKm < 4 ? (isDay ? 'Bật đèn sương mù' : 'Kiểm tra đèn chiếu sáng') : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Nắng nóng',\n",
        "        threshold: '≥31°C',\n",
        "        current: curTemp != null ? `${curTemp.toFixed(1)}°C` : '\u2014',\n",
        "        trend: `60 phút tới: ${nxtTemp.toFixed(1)}°C`,\n",
        "        level: nxtTemp >= 35 ? 'danger' : (nxtTemp >= 31 ? 'warn' : 'ok'),\n",
        "        advice: nxtTemp >= 35 ? 'Che nắng, tránh say nắng' : 'Bình thường'\n",
        "      }\n",
        "    ];\n",
        "    \n",
        "    tbody.innerHTML = rows.map(r => `\n",
        "      <tr>\n",
        "        <td>${r.name}</td>\n",
        "        <td>${r.threshold}</td>\n",
        "        <td>${r.current}</td>\n",
        "        <td>${r.trend}</td>\n",
        "        <td><span class=\"dash-badge ${r.level}\">${r.level === 'danger' ? 'Nguy hiểm' : r.level === 'warn' ? 'Cảnh báo' : 'Ổn định'}</span></td>\n",
        "        <td>${r.advice}</td>\n",
        "      </tr>\n",
        "    `).join('');\n",
        "  }\n",
        "\n",
        "  function renderFarmDashboard() {\n",
        "    const table = $('farmDashTable');\n",
        "    if (!table || !RT.current) return;\n",
        "    const tbody = table.querySelector('tbody');\n",
        "    if (!tbody) return;\n",
        "\n",
        "    const next = getInterpolated24h().slice(0, 1);\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? null;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const nxt = next[0] || {};\n",
        "    const nxtTemp = nxt.temp ?? curTemp;\n",
        "    const nxtWind = mps2kmh(nxt.wind || (cur.wind?.speed ?? 0));\n",
        "    const nxtPop = Math.round((nxt.pop || 0) * 100);\n",
        "    const nxtHasStorm = (nxt.weather?.id || 0) >= 200 && (nxt.weather?.id || 0) < 300;\n",
        "\n",
        "    const rows = [\n",
        "      {\n",
        "        name: 'Nắng nóng',\n",
        "        threshold: '≥35°C',\n",
        "        current: curTemp != null ? `${curTemp.toFixed(1)}°C` : '\u2014',\n",
        "        trend: `60 phút tới: ${nxtTemp.toFixed(1)}°C`,\n",
        "        level: nxtTemp >= 35 ? 'danger' : (nxtTemp >= 33 ? 'warn' : 'ok'),\n",
        "        advice: nxtTemp >= 35 ? (isDay ? 'Tưới nước sáng sớm, che lưới' : 'Chuẩn bị tưới sáng mai') : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Mưa lớn',\n",
        "        threshold: '≥10mm/h hoặc ≥70%',\n",
        "        current: `${curRain.toFixed(1)} mm/h \u00b7 ${curPop}%`,\n",
        "        trend: `60 phút tới: ${nxtPop}%`,\n",
        "        level: (curRain >= 10 || nxtPop >= 70) ? 'danger' : (nxtPop >= 50 ? 'warn' : 'ok'),\n",
        "        advice: (curRain >= 10 || nxtPop >= 70) ? 'Chủ động thoát nước' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Gió mạnh',\n",
        "        threshold: '≥28 km/h',\n",
        "        current: `${curWind} km/h`,\n",
        "        trend: `60 phút tới: ${nxtWind} km/h`,\n",
        "        level: nxtWind >= 28 ? 'danger' : (nxtWind >= 22 ? 'warn' : 'ok'),\n",
        "        advice: nxtWind >= 28 ? 'Gia cố giàn, cọc' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Dông sét',\n",
        "        threshold: 'Mã 2xx',\n",
        "        current: nxtHasStorm ? 'Có dông' : 'Không',\n",
        "        trend: nxtHasStorm ? '60 phút tới: rủi ro cao' : 'Ổn định',\n",
        "        level: nxtHasStorm ? 'danger' : 'ok',\n",
        "        advice: nxtHasStorm ? 'Tránh phun xịt/ra đồng' : 'Bình thường'\n",
        "      }\n",
        "    ];\n",
        "\n",
        "    tbody.innerHTML = rows.map(r => `\n",
        "      <tr>\n",
        "        <td>${r.name}</td>\n",
        "        <td>${r.threshold}</td>\n",
        "        <td>${r.current}</td>\n",
        "        <td>${r.trend}</td>\n",
        "        <td><span class=\"dash-badge ${r.level}\">${r.level === 'danger' ? 'Nguy hiểm' : r.level === 'warn' ? 'Cảnh báo' : 'Ổn định'}</span></td>\n",
        "        <td>${r.advice}</td>\n",
        "      </tr>\n",
        "    `).join('');\n",
        "  }\n",
        "\n",
        "  function renderAquaDashboard() {\n",
        "    const table = $('aquaDashTable');\n",
        "    if (!table || !RT.current) return;\n",
        "    const tbody = table.querySelector('tbody');\n",
        "    if (!tbody) return;\n",
        "\n",
        "    const next = getInterpolated24h().slice(0, 1);\n",
        "    const cur = RT.current;\n",
        "    const curTemp = cur.main?.temp ?? null;\n",
        "    const curWind = mps2kmh(cur.wind?.speed || 0);\n",
        "    const curRain = cur.rain?.['1h'] || cur.rain?.['3h'] || 0;\n",
        "    const curPop = Math.round(((RT.forecast?.list?.[0]?.pop ?? 0) * 100));\n",
        "    const isDay = isDayNow();\n",
        "\n",
        "    const nxt = next[0] || {};\n",
        "    const nxtTemp = nxt.temp ?? curTemp;\n",
        "    const nxtWind = mps2kmh(nxt.wind || (cur.wind?.speed ?? 0));\n",
        "    const nxtPop = Math.round((nxt.pop || 0) * 100);\n",
        "    const nxtHasStorm = (nxt.weather?.id || 0) >= 200 && (nxt.weather?.id || 0) < 300;\n",
        "\n",
        "    const nearestStAqua = getNearestStationData();\n",
        "    const waterLvlAqua = nearestStAqua ? parseFloat(nearestStAqua.waterLevel) : null;\n",
        "\n",
        "    const rows = [\n",
        "      {\n",
        "        name: 'Triều cường',\n",
        "        threshold: '>2.5m',\n",
        "        current: waterLvlAqua != null ? waterLvlAqua.toFixed(2) + 'm' : '\u2014',\n",
        "        trend: `Trạm: ${nearestStAqua ? nearestStAqua.name : '\u2014'}`,\n",
        "        level: waterLvlAqua != null && waterLvlAqua > 2.5 ? 'danger' : (waterLvlAqua != null && waterLvlAqua > 2.0 ? 'warn' : 'ok'),\n",
        "        advice: waterLvlAqua != null && waterLvlAqua > 2.5 ? (isDay ? '⚠️ Gia cố bờ bao' : '⚠️ Kiểm tra bờ bao bằng đèn pin') : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Mưa lớn',\n",
        "        threshold: '≥10mm/h hoặc ≥70%',\n",
        "        current: `${curRain.toFixed(1)} mm/h \u00b7 ${curPop}%`,\n",
        "        trend: `60 phút tới: ${nxtPop}%`,\n",
        "        level: (curRain >= 10 || nxtPop >= 70) ? 'danger' : (nxtPop >= 50 ? 'warn' : 'ok'),\n",
        "        advice: (curRain >= 10 || nxtPop >= 70) ? 'Chống sốc nước/độ mặn' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Gió mạnh',\n",
        "        threshold: '≥28 km/h',\n",
        "        current: `${curWind} km/h`,\n",
        "        trend: `60 phút tới: ${nxtWind} km/h`,\n",
        "        level: nxtWind >= 28 ? 'danger' : (nxtWind >= 22 ? 'warn' : 'ok'),\n",
        "        advice: nxtWind >= 28 ? 'Hạn chế cho ăn, gia cố' : 'Bình thường'\n",
        "      },\n",
        "      {\n",
        "        name: 'Nhiệt nước',\n",
        "        threshold: '≥31°C',\n",
        "        current: curTemp != null ? `${curTemp.toFixed(1)}°C` : '\u2014',\n",
        "        trend: `60 phút tới: ${nxtTemp.toFixed(1)}°C`,\n",
        "        level: nxtTemp >= 31 ? 'warn' : 'ok',\n",
        "        advice: nxtTemp >= 31 ? (isDay ? 'Sục khí/che mát' : 'Tăng oxy hòa tan đêm') : 'Bình thường'\n",
        "      }\n",
        "    ];\n",
        "\n",
        "    tbody.innerHTML = rows.map(r => `\n",
        "      <tr>\n",
        "        <td>${r.name}</td>\n",
        "        <td>${r.threshold}</td>\n",
        "        <td>${r.current}</td>\n",
        "        <td>${r.trend}</td>\n",
        "        <td><span class=\"dash-badge ${r.level}\">${r.level === 'danger' ? 'Nguy hiểm' : r.level === 'warn' ? 'Cảnh báo' : 'Ổn định'}</span></td>\n",
        "        <td>${r.advice}</td>\n",
        "      </tr>\n",
        "    `).join('');\n",
        "  }\n"
    ]
    
    new_lines = lines[:start_idx] + clean_code + lines[end_idx:]
    
    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        f.writelines(new_lines)
    
    print("Successfully cleaned the section and implemented 60-minute real-time day/night advice.")
else:
    print("FAILED to find marks.")
